version: '3'

tasks:
  build:
    desc: Build the Go project
    cmds:
      - go build ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linter
    cmds:
      - go vet ./...
      - test -z "$(gofmt -l .)"